version: '3.8'

services:
  # 定义我们的主服务
  telebot-dispatch-center:
    # 使用当前目录下的 Dockerfile 来构建镜像
    build: .
    # 给容器起个名字，方便管理
    container_name: telebot_dispatch_center
    # 设置重启策略，如果容器意外退出，会自动重启
    restart: always
    # 加载 .env 文件中的环境变量
    env_file:
      - .env
    # 将服务器的 80 端口映射到容器的 8000 端口
    # 这样用户就可以通过 http://YOUR_SERVER_IP 直接访问
    ports:
      - "80:8000"
    # 将服务器上的 ./output 目录挂载到容器的 /app/output 目录
    # (虽然这个服务不直接生成文件，但保留这个可以方便未来扩展)
    volumes:
      - ./output:/app/output

